model:
  name: HCLRNet
  task: UnderWater Image Enhance
  struct:
    name: HCLRNet
    input_nc: 3
    ngf: 64


data:
  dir: Datasets/UnderWater
  dataset_type: HCLRDataset
  is_multi_loader: true
  train_transforms:
  train_target_transforms:
  test_transforms:
  test_target_transforms:
  crop_size: 256

optim:
  optimizer:
    name: AdamW
    lr: 0.0001
    betas:
      - 0.900
      - 0.999
    weight_decay: 0.001
  scheduler:
    name: CyclicLR
    base_lr: 0.0001
    max_lr: 0.00015
    cycle_momentum: false

loss:
  loss_terms:
    name: HCLRLoss

trainer:
  name: HCLRTrainer
  ckpt_dir: checkpoints
  resume_ckpt:
  batch_size: 16
  batch_size_per_gpu:
  batch_size_test: 1
  batch_size_per_gpu_test:
  num_workers_per_gpu: 8
  drop_last: true
  pin_memory: true
  scaler: native
  save_freq: 1
  sync_bn: false
  dist_bn:
  amp: true

logger:
  dir: logs
  log_freq: 100
  logger_rank: 0

seed: 42
total_epochs: 500
warmup_epochs: 0
test_start_epoch: 1
